reminder/profiles/urls.py
from django.conf.urls import url
from profiles import views
urlpatterns = [
    url(r'^$', views.index, name='profiles')
]

reminder/reminder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('profiles.urls', namespace='profiles')),
    url(r'^reminder/', include('reminders.urls', namespace='reminders')),
]

reminder/reminders/urls.py
from django.conf.urls import url
from reminders import views
urlpatterns = [
    url(r'^$', views.add_group, name='group'),
    url(r'^(?P<group_id>[0-9]+)/reminders_add/$', views.add_reminders, name='reminder'),
    url(r'(?P<group_idi>[0-9]+)/group$', views.reminders_page, name='reminderss'),
    url(r'(?P<del_id>[0-9]+)/delete_remind$', views.del_remind, name='delremind'),
]

reminder/note/models.py
#coding: utf-8
from __future__ import unicode_literals
from django.utils.translation import ugettext as _
from django.db import models
from profiles.models import Profile
from django.utils import timezone


class Group(models.Model):
    user = models.ManyToManyField(Profile, verbose_name=_('Профиль'), default=None, null=True, blank=True, related_name='profile')
    name = models.CharField(max_length=50, verbose_name=_('Название'), default=None, null=True)

    def __unicode__(self):
        return unicode(self.name) or u''

    class Meta:
        verbose_name = _('Группа')
        verbose_name_plural = _('Группы')

class Reminder(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('Название'), default=None, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    date_of_publish = models.DateTimeField(verbose_name=_('Дата Публикации'), default=timezone.now(), null=True, blank=True)
    date_of_start = models.DateTimeField(verbose_name=_('Дата Публикации'), default=timezone.now(), null=True, blank=True)
    group = models.ForeignKey(Group, verbose_name=_('Группа'), related_name='reminder')

    def __unicode__(self):
        return unicode(self.name) or u''

    class Meta:
        verbose_name = _('Напоминание')
        verbose_name_plural = _('Напоминании')

reminder/profiles/models.py
#coding: utf-8
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext as _


class Profile(AbstractUser):
    name = models.CharField(max_length=50, verbose_name=_('Имя'))

    class Meta:
        verbose_name = _('Профиль')
        swappable = 'AUTH_USER_MODEL'
        verbose_name_plural = _('Профили')

reminder/reminders/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

reminder/reminders/forms.py
from django import forms
from note.models import Group, Reminder

class CreateGroup(forms.ModelForm):

    class Meta:
        model = Group
        fields = ('name', 'user',)


class CreateIncome(forms.ModelForm):
    class Meta:
        model = Reminder
        fields = ('date_of_start', )

reminder/note/views.py
from django.shortcuts import render

# Create your views here.

reminder/profiles/views.py
from django.shortcuts import render
from note.models import Reminder, Group

def index(request):
    return render(request, 'main/index.html', {})

reminder/reminders/views.py
#coding: utf-8
from django.shortcuts import render
from note.models import Reminder, Group
from profiles.models import Profile
from reminders.forms import CreateGroup
from django.shortcuts import redirect
from django.contrib import messages
from profiles import views
from reminders.forms import CreateIncome


def add_group(request):
    profile = Profile.objects.all()
    if request.POST:
        create = Group.objects.create(name=request.POST['message'])
        for i in request.POST.getlist('browser'):
            create.user.add(int(i))
        messages.success(request, 'Спасибо вы создали группу')
        return redirect('reminders:reminderss', group_idi=int(create.id))
    return render(request, 'reminder/add_group.html', {'profile': profile})


def add_reminders(request, group_id):
    forms = CreateIncome()
    forms = CreateIncome(request.POST or None)
    if forms.is_valid():
        forms = forms.save(commit=False)
        forms.name = request.POST['name']
        forms.text = request.POST['message']
        forms.group = Group.objects.get(pk=int(group_id))
        # create = Reminder.objects.create(name=request.POST['name'], text = request.POST['message'] , group=Group.objects.get(pk=int(group_id)))
        forms.save()
        return redirect('reminders:reminderss', group_idi=group_id)
    return render(request, 'reminder/add_reminder.html', {'forms': forms})


def reminders_page(request, group_idi):
    group_id = int(group_idi)
    return render(request, 'reminder/reminder.html', {'gr_id': group_id})


def del_remind(request, del_id):
    if 1 == 1:
        delete = Reminder.objects.get(pk=del_id)
        group = delete.group
        group.user.remove(request.user)
        return redirect('profiles:profiles')
    return render(request, 'reminder/delete_reminder.html', {})

reminder/templates/main/index.html
<a href="{% url 'reminders:group' %}">Создать группу</a>	
<p>{{request.user.username}}</p>
Напоминании: {% for i in request.user.profile.all %}
{% for i in i.reminder.all %}
  <p>{{ i.name }}    дата: {{ i.date_of_publish }}
<a href="{% url 'reminders:delremind' i.id %}">&times;</a>
{% endfor %}	
{% endfor %}
<p>Мои группы:</p>
{% for i in request.user.profile.all %}
	
<a href="{% url 'reminders:reminderss' i.id  %}">{{ i.name }}</a>
{% endfor %} 

reminder/templates/reminder/add_group.html
<form method="POST">
{% csrf_token %}
<input type="text" name="message">
{% for i in profile %}
<input type="checkbox" name="browser" value="{{ i.id }}">{{ i.username }}
{% endfor %}
<button>Save</Button>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

reminder/templates/reminder/add_reminder.html
<form method="POST">
{% csrf_token %}
{{ forms.as_p }}
Названия
<input type="text" name="name">
Описания
<input type="text" name="message">

<button>Save</button>
</form>

reminder/templates/reminder/reminder.html
<a href="{% url 'reminders:reminder' gr_id  %}">создать напоминания</a>